// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mx6YKj8cB0p5c3436d5ZBNnsHcGVBNE',
    appId: '1:1014219573046:web:f024b1275ce04cd193d597',
    messagingSenderId: '1014219573046',
    projectId: 'wordsort-2bea3',
    authDomain: 'wordsort-2bea3.firebaseapp.com',
    storageBucket: 'wordsort-2bea3.appspot.com',
    measurementId: 'G-2SGESKYVB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXyByDVr4isnSCYg43Q47zJX5Dt77_-kY',
    appId: '1:1014219573046:android:e7fe595d1866ad2493d597',
    messagingSenderId: '1014219573046',
    projectId: 'wordsort-2bea3',
    storageBucket: 'wordsort-2bea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF6zJXs4BnLhogr_YF8dUqERayt1Y1qow',
    appId: '1:1014219573046:ios:7ef4b3a2d5736a8b93d597',
    messagingSenderId: '1014219573046',
    projectId: 'wordsort-2bea3',
    storageBucket: 'wordsort-2bea3.appspot.com',
    iosClientId: '1014219573046-klq0n3iio9d9vev24idtil9j26iabivt.apps.googleusercontent.com',
    iosBundleId: 'com.wordsort.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF6zJXs4BnLhogr_YF8dUqERayt1Y1qow',
    appId: '1:1014219573046:ios:7ef4b3a2d5736a8b93d597',
    messagingSenderId: '1014219573046',
    projectId: 'wordsort-2bea3',
    storageBucket: 'wordsort-2bea3.appspot.com',
    iosClientId: '1014219573046-klq0n3iio9d9vev24idtil9j26iabivt.apps.googleusercontent.com',
    iosBundleId: 'com.wordsort.app',
  );
}
